[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
tokio = { version = "1.47.1", features = ["full"] }
tokio-tungstenite = "0.24.0"
url = "2.5.4"
ratatui = "0.26.0"
crossterm = "0.27.0"
